package toptal.legacy.business.persistence.sql.entities;
// Generated 19-mar-2016 17:09:32 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import toptal.common.business.persistence.facade.entities.OrderDetail;
import toptal.common.business.persistence.pk.OrderDetailPK;

/**
 * OrderDetail generated by hbm2java 
 */
@Entity
@Table(name = "ORDER_DETAIL")
public class OrderDetailSQL implements java.io.Serializable, OrderDetail {

	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	private OrderDetailPK orderDetailPK;
	
	@Column(name = "PRICE", nullable = false, precision = 10, scale = 0)
	private float price;
	
	@Column(name = "PRODUCT_DESCRIPTION", nullable = false)
	private String productDescription;

	public OrderDetailSQL() {
	}

	public OrderDetailSQL(OrderDetailPK orderDetailPK, long price, String productDescription) {
		this.orderDetailPK = orderDetailPK;
		this.price = price;
		this.productDescription = productDescription;
	}

	public OrderDetailPK getOrderDetailPK() {
		return this.orderDetailPK;
	}

	public void setOrderDetailPK(OrderDetailPK orderDetailPK) {
		this.orderDetailPK = orderDetailPK;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float f) {
		this.price = f;
	}

	public String getProductDescription() {
		return this.productDescription;
	}

	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

}
