package toptal.spring.business.persistence.nosql.entities;

import java.util.Date;

import toptal.common.business.persistence.facade.entities.Customer;
import toptal.common.business.persistence.facade.entities.CustomerOrder;

/**
 * CustomerOrder generated by hbm2java
 */
public class CustomerOrderNoSQL implements java.io.Serializable, CustomerOrder {

	private static final long serialVersionUID = 1L;
	
	private long orderId;
	private float price;
	private float usdChangeRate;
	private Customer customer;
	private Long deliveryAddress;
	private Date placementDate;

	public CustomerOrderNoSQL() {
	}

	public CustomerOrderNoSQL(long orderId) {
		this.orderId = orderId;
	}

	public CustomerOrderNoSQL(long orderId, CustomerNoSQL customer, Long deliveryAddress) {
		this.orderId = orderId;
		this.customer = customer;
		this.deliveryAddress = deliveryAddress;
	}

	public Date getPlacementDate() {
		return placementDate;
	}

	public void setPlacementDate(Date placementDate) {
		this.placementDate = placementDate;
	}

	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Long getDeliveryAddress() {
		return this.deliveryAddress;
	}

	public void setDeliveryAddress(Long deliveryAddress) {
		this.deliveryAddress = deliveryAddress;
	}

	public float getPrice() {
		return price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public float getUsdChangeRate() {
		return usdChangeRate;
	}

	public void setUsdChangeRate(float usdChangeRate) {
		this.usdChangeRate = usdChangeRate;
	}

}
