package toptal.business.persistence.nosql.entities;

import toptal.business.persistence.facade.entities.ProductByUser;
import toptal.business.persistence.pk.ProductByUserPK;

/**
* Product generated by hbm2java
*/
public class ProductByUserNoSQL implements java.io.Serializable, ProductByUser{
	
	private static final long serialVersionUID = 1L;
	
	private ProductByUserPK productByUserPK;


	public ProductByUserPK getProductByUserPK() {
		return productByUserPK;
	}

	public void setProductByUserPK(ProductByUserPK productByUserPK) {
		this.productByUserPK = productByUserPK;
	}
}
