package toptal.business.persistence.sql.entities;
// Generated 19-mar-2016 17:09:32 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import toptal.business.persistence.facade.entities.Customer;
import toptal.business.persistence.facade.entities.CustomerOrder;
import toptal.business.persistence.facade.entities.Product;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "CUSTOMER")
public class CustomerSQL implements java.io.Serializable, Customer {

	private static final long serialVersionUID = 1L;
	
	private long customerId;
	private String name;
	private String email;
	private Set<CustomerOrderSQL> customerOrders = new HashSet<CustomerOrderSQL>(0);
	private Set<ProductSQL> products = new HashSet<ProductSQL>(0);

	public CustomerSQL() {
	}

	public CustomerSQL(long customerId, String name, String email) {
		this.customerId = customerId;
		this.name = name;
		this.email = email;
	}

	public CustomerSQL(long customerId, String name, String email, Set<CustomerOrderSQL> customerOrders,
			Set<ProductSQL> products) {
		this.customerId = customerId;
		this.name = name;
		this.email = email;
		this.customerOrders = customerOrders;
		this.products = products;
	}

	@Id
	@Column(name = "CUSTOMER_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	@Column(name = "NAME", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "EMAIL", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<CustomerOrderSQL> getCustomerOrders() {
		return this.customerOrders;
	}

	public void setCustomerOrders(Set<CustomerOrderSQL> customerOrders) {
		this.customerOrders = customerOrders;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "customers")
	public Set<ProductSQL> getProducts() {
		return this.products;
	}

	public void setProducts(Set<ProductSQL> products) {
		this.products = products;
	}
}
