package toptal.business.persistence.sql.entities;
// Generated 19-mar-2016 17:09:32 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import toptal.business.persistence.facade.entities.CustomerOrder;

/**
 * CustomerOrder generated by hbm2java
 */
@Entity
@Table(name = "CUSTOMER_ORDER")
public class CustomerOrderSQL implements java.io.Serializable, CustomerOrder {

	private static final long serialVersionUID = 1L;
	
	private long orderId;
	private float price;
	private float usdChangeRate;
	private CustomerSQL customer;
	private Long deliveryAddress;
	private Date placementDate;

	public CustomerOrderSQL() {
	}

	public CustomerOrderSQL(long orderId) {
		this.orderId = orderId;
	}

	public CustomerOrderSQL(long orderId, CustomerSQL customer, Long deliveryAddress) {
		this.orderId = orderId;
		this.customer = customer;
		this.deliveryAddress = deliveryAddress;
	}

	@Column(name = "PLACEMENT_DATE", nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	public Date getPlacementDate() {
		return placementDate;
	}

	public void setPlacementDate(Date placementDate) {
		this.placementDate = placementDate;
	}

	@Id
	@Column(name = "ORDER_ID", unique = true, nullable = false, precision = 10, scale = 0)
	@GeneratedValue(generator="CUS_ORD_SEQ")
	@SequenceGenerator(name="CUS_ORD_SEQ",sequenceName="CUSTOMER_ORDER_SEQ")
	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ID")
	public CustomerSQL getCustomer() {
		return this.customer;
	}

	public void setCustomer(CustomerSQL customer) {
		this.customer = customer;
	}

	@Column(name = "DELIVERY_ADDRESS", precision = 10, scale = 0)
	public Long getDeliveryAddress() {
		return this.deliveryAddress;
	}

	public void setDeliveryAddress(Long deliveryAddress) {
		this.deliveryAddress = deliveryAddress;
	}

	@Column(name = "PRICE", nullable = false, precision = 10, scale = 0)
	public float getPrice() {
		return price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@Column(name = "USD_CHANGE_RATE", nullable = false, precision = 10, scale = 0)
	public float getUsdChangeRate() {
		return usdChangeRate;
	}

	public void setUsdChangeRate(float usdChangeRate) {
		this.usdChangeRate = usdChangeRate;
	}

}
