package toptal.business.persistence.sql.entities;
// Generated 19-mar-2016 17:09:32 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import toptal.business.persistence.facade.entities.Product;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT")
public class ProductSQL implements java.io.Serializable, Product {

	private static final long serialVersionUID = 1L;
	
	private long productId;
	private String name;
	private float price;
	private Set<CustomerSQL> customers = new HashSet<CustomerSQL>(0);

	public ProductSQL() {
	}

	public ProductSQL(long productId, String name, long price) {
		this.productId = productId;
		this.name = name;
		this.price = price;
	}

	public ProductSQL(long productId, String name, long price, Set<CustomerSQL> customers) {
		this.productId = productId;
		this.name = name;
		this.price = price;
		this.customers = customers;
	}

	@Id
	@Column(name = "PRODUCT_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getProductId() {
		return this.productId;
	}

	public void setProductId(long productId) {
		this.productId = productId;
	}

	@Column(name = "NAME", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PRICE", nullable = false, precision = 10, scale = 0)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "PRODUCT_BY_USER", joinColumns = {
			@JoinColumn(name = "PRODUCT_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "CUSTOMER_ID", nullable = false, updatable = false) })
	public Set<CustomerSQL> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<CustomerSQL> customers) {
		this.customers = customers;
	}

}
