package test.persistence.entities;

// Generated 23-jul-2015 17:12:44 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios", schema = "test")
public class Usuarios implements java.io.Serializable {

	private Integer usuId;
	private String usuNomUsu;
	private String usuApeUsu;
	private String usuCedUsu;
	private String usuCorUsu;
	private String usuTelUsu;
	private String usuDirUsu;

	public Usuarios() {
	}

	public Usuarios(String usuNomUsu, String usuApeUsu, String usuCedUsu,
			String usuCorUsu, String usuTelUsu, String usuDirUsu) {
		this.usuNomUsu = usuNomUsu;
		this.usuApeUsu = usuApeUsu;
		this.usuCedUsu = usuCedUsu;
		this.usuCorUsu = usuCorUsu;
		this.usuTelUsu = usuTelUsu;
		this.usuDirUsu = usuDirUsu;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USU_ID", unique = true, nullable = false)
	public Integer getUsuId() {
		return this.usuId;
	}

	public void setUsuId(Integer usuId) {
		this.usuId = usuId;
	}

	@Column(name = "USU_NOM_USU", nullable = false, length = 45)
	public String getUsuNomUsu() {
		return this.usuNomUsu;
	}

	public void setUsuNomUsu(String usuNomUsu) {
		this.usuNomUsu = usuNomUsu;
	}

	@Column(name = "USU_APE_USU", nullable = false, length = 45)
	public String getUsuApeUsu() {
		return this.usuApeUsu;
	}

	public void setUsuApeUsu(String usuApeUsu) {
		this.usuApeUsu = usuApeUsu;
	}

	@Column(name = "USU_CED_USU", nullable = false, length = 45)
	public String getUsuCedUsu() {
		return this.usuCedUsu;
	}

	public void setUsuCedUsu(String usuCedUsu) {
		this.usuCedUsu = usuCedUsu;
	}

	@Column(name = "USU_COR_USU", nullable = false, length = 45)
	public String getUsuCorUsu() {
		return this.usuCorUsu;
	}

	public void setUsuCorUsu(String usuCorUsu) {
		this.usuCorUsu = usuCorUsu;
	}

	@Column(name = "USU_TEL_USU", nullable = false, length = 10)
	public String getUsuTelUsu() {
		return this.usuTelUsu;
	}

	public void setUsuTelUsu(String usuTelUsu) {
		this.usuTelUsu = usuTelUsu;
	}

	@Column(name = "USU_DIR_USU", nullable = false, length = 45)
	public String getUsuDirUsu() {
		return this.usuDirUsu;
	}

	public void setUsuDirUsu(String usuDirUsu) {
		this.usuDirUsu = usuDirUsu;
	}

}
